### ISSUE TITLE
add support for managed identity

### ISSUE THREAD

**Issue by sozercan** [Azure/rg-cleanup#13]

**Comment by CecileRobertMichon** [comment]
I circled back to this finally and made some progress but still couldn't get it to work. Fetching the token fails with "managed identity timed out".

What's strange is that the code itself is working if I run it on a VM with a managed ID assigned, and I tested that creating a managed identity enabled ACI with the logic app from the docs example image works as well if I exec into the container and use Azure CLI. So I think something about how we build the image is causing the issue.
